---
- name: restart llama-server
  ansible.builtin.systemd:
    name: llama-server
    state: restarted
    daemon_reload: true

- name: restart tegrastats-exporter
  ansible.builtin.systemd:
    name: tegrastats-exporter
    state: restarted
    daemon_reload: true

- name: reboot board
  ansible.builtin.reboot:
    reboot_timeout: 300
