"""POST /v1/tokenize/fertility — {text} → per-tokenizer counts/segments (powers the 3D hero)."""

from __future__ import annotations

from typing import Any

from fastapi import APIRouter, HTTPException, Request
from pydantic import BaseModel, Field

from sanad_api.core.security import RateLimited
from sanad_api.services.fertility import load_static_report, measure

router = APIRouter(prefix="/v1/tokenize", tags=["tokenize"])

MAX_CHARS = 2000  # hero budget: ≤1200 glyphs; be generous but bounded


class FertilityRequest(BaseModel):
    text: str = Field(min_length=1, max_length=MAX_CHARS)


@router.post("/fertility")
async def fertility(req: FertilityRequest, request: Request, _: RateLimited) -> dict[str, Any]:
    settings = request.app.state.settings
    result = await measure(settings.tokenizers_dir, req.text)
    if not result["tokenizers"]:
        raise HTTPException(
            status_code=503,
            detail="no tokenizers available — sync tokenizer.json files to SANAD_TOKENIZERS_DIR",
        )
    return result


@router.get("/fertility/report")
async def fertility_report(request: Request) -> dict[str, Any]:
    """The frozen corpus-level fertility.json generated by `just fertility` (never hand-edited)."""
    settings = request.app.state.settings
    report = load_static_report(settings.fertility_report_path)
    if report is None:
        raise HTTPException(status_code=404, detail="fertility report not generated yet")
    return report
